title: "Darwish Fawaz"

description: "Infrastructure & Security Architect"

url: "https://darwishfawaz.github.io"
baseurl: ""

author:
  name: "Darwish Fawaz"

markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules